from query import *

pessoas = Table('Pessoas')
pessoas.add_column('Nome')
pessoas.add_column('Idade')
pessoas.add_instance(["Gilmar",43])
pessoas.add_instance(["Ana",29])
pessoas.add_instance(["Gabriela",12])
pessoas.add_instance(["Vandro",25])
pessoas.add_instance(["Leia",56])
pessoas.add_instance(["Julia",35])
database.append(pessoas)
carro = Table('Carro')
carro.add_column('Cor')
carro.add_column('Idade')
carro.add_instance(["Toyota",29])
carro.add_instance(["Mitono",35])
database.append(carro)
