EQUAL = '=='
NOT_EQUAL = '!='
GREATER = '>'
LESSER = '<'
NOT = '!'
AND = ' e '
OR = ' ou '
SET = ' = '
SEPARATE = ','
MULTIPLY = '*'
DIVIDE = '/'
SUM = '+'
SUBTRACT = '-'

SELECT = ' própega '
FROM = ' ladi '
WHERE = ' com '
ORDER_BY = ' ordenado '
ASC = ' di cima '
DESC = ' di baixo '
INSERT_INTO = ' coloca em '
VALUE = ' valor '
ON = ' em '
JOIN = ' junta '
DELETE = ' acaba '
UPDATE = ' muda '
SET_TEXT = ' dexa '
